## A7 CDS 0MM

In [11]:
import pandas as pd

df_a7_0mm_cds = pd.read_csv('output/km_a7_0mm_cds_alignment.sam', sep='\t',
                names=['query_name', 'strand', 'reference_name', 'mapping_position',
                       'Sequence', 'mapping_quality', 'idk', 'mismatch'])
df_a7_0mm_cds

,query_name,strand,reference_name,mapping_position,Sequence,mapping_quality,idk,mismatch
0,READ_3,+,lcl|NC_036025.1_cds_XP_022674188.1_649,618,ACCAAGTGGATTGGTGGTCATGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
1,READ_8,+,lcl|NC_036032.1_cds_XP_022678348.1_4817,1512,ACTCATTTGACACCAGCTATGGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
2,READ_11,+,lcl|NC_036025.1_cds_XP_022673914.1_374,273,ATTGGTGGTGCCATTGGTACTGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
3,READ_15,+,lcl|NC_036025.1_cds_XP_022674188.1_649,609,CACTCTGCTACCAAGTGGATTGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
4,READ_19,-,lcl|NC_036025.1_cds_XP_022673643.1_103,1434,CCATTCAAGGCCAAGTTCATGCC,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
5,READ_21,-,lcl|NC_036032.1_cds_XP_022678348.1_4817,1389,CCTATCCAAAGAGATATGTTCAC,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
6,READ_27,+,lcl|NC_036025.1_cds_XP_022674188.1_649,612,TCTGCTACCAAGTGGATTGGTGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
7,READ_29,+,lcl|NC_036032.1_cds_XP_022678348.1_4817,2019,TTATACAGAACTGGTGATTTAGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN

## A7 CDS 1MM

In [12]:
df_a7_1mm_cds = pd.read_csv('output/km_a7_1mm_cds_alignment.sam', sep='\t',
                names=['query_name', 'strand', 'reference_name', 'mapping_position',
                       'Sequence', 'mapping_quality', 'idk', 'mismatch'])
df_a7_1mm_cds

,query_name,strand,reference_name,mapping_position,Sequence,mapping_quality,idk,mismatch
0,READ_1,+,lcl|NC_036025.1_cds_XP_022674188.1_649,618,ACCAAGTGGATTGGTGGTCAAGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>A
1,READ_2,+,lcl|NC_036025.1_cds_XP_022674188.1_649,618,ACCAAGTGGATTGGTGGTCACGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>C
2,READ_3,+,lcl|NC_036025.1_cds_XP_022674188.1_649,618,ACCAAGTGGATTGGTGGTCATGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
3,READ_4,+,lcl|NC_036025.1_cds_XP_022674188.1_649,618,ACCAAGTGGATTGGTGGTCAGGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>G
4,READ_5,+,lcl|NC_036032.1_cds_XP_022678348.1_4817,1512,ACTCATTTGACACCAGCTATAGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:G>A
5,READ_6,+,lcl|NC_036032.1_cds_XP_022678348.1_4817,1512,ACTCATTTGACACCAGCTATCGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:G>C
6,READ_7,+,lcl|NC_036032.1_cds_XP_022678348.1_4817,1512,ACTCATTTGACACCAGCTATTGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:G>T
7,READ_8,+,lcl|NC_036032.1_cds_XP_022678348.1_4817,1512,ACTCATTTGACACCAGCTATGGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
8,READ_9,+,lcl|NC_036025.1_cds_XP_022673914.1_374,273,ATTGGTGGTGCCATTGGTACAGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>A
9,READ_10,+,lcl|NC_036025.1_cds_XP_022673914.1_374,273,ATTGGTGGTGCCATTGGTACCGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>C
10,READ_11,+,lcl|NC_036025.1_cds_XP_022673914.1_374,273,ATTGGTGGTGCCATTGGTACTGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
11,READ_12,+,lcl|NC_036025.1_cds_XP_022673914.1_374,273,ATTGGTGGTGCCATTGGTACGGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>G
12,READ_13,+,lcl|NC_036025.1_cds_XP_022674188.1_649,609,CACTCTGCTACCAAGTGGATAGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>A
13,READ_14,+,lcl|NC_036025.1_cds_XP_022674188.1_649,609,CACTCTGCTACCAAGTGGATCGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>C
14,READ_15,+,lcl|NC_036025.1_cds_XP_022674188.1_649,609,CACTCTGCTACCAAGTGGATTGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
15,READ_16,+,lcl|NC_036025.1_cds_XP_022674188.1_649,609,CACTCTGCTACCAAGTGGATGGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>G
16,READ_17,-,lcl|NC_036025.1_cds_XP_022673643.1_103,1434,CCTTTCAAGGCCAAGTTCATGCC,IIIIIIIIIIIIIIIIIIIIIII,0,20:A>T
17,READ_18,-,lcl|NC_036025.1_cds_XP_022673643.1_103,1434,CCGTTCAAGGCCAAGTTCATGCC,IIIIIIIIIIIIIIIIIIIIIII,0,20:A>G
18,READ_19,-,lcl|NC_036025.1_cds_XP_022673643.1_103,1434,CCATTCAAGGCCAAGTTCATGCC,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
19,READ_20,-,lcl|NC_036025.1_cds_XP_022673643.1_103,1434,CCCTTCAAGGCCAAGTTCATGCC,IIIIIIIIIIIIIIIIIIIIIII,0,20:A>C
20,READ_21,-,lcl|NC_036032.1_cds_XP_022678348.1_4817,1389,CCTATCCAAAGAGATATGTTCAC,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
21,READ_22,-,lcl|NC_036032.1_cds_XP_022678348.1_4817,1389,CCGATCCAAAGAGATATGTTCAC,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>G
22,READ_23,-,lcl|NC_036032.1_cds_XP_022678348.1_4817,1389,CCAATCCAAAGAGATATGTTCAC,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>A
23,READ_24,-,lcl|NC_036032.1_cds_XP_022678348.1_4817,1389,CCCATCCAAAGAGATATGTTCAC,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>C
24,READ_25,+,lcl|NC_036025.1_cds_XP_022674188.1_649,612,TCTGCTACCAAGTGGATTGGAGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>A
25,READ_26,+,lcl|NC_036025.1_cds_XP_022674188.1_649,612,TCTGCTACCAAGTGGATTGGCGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>C
26,READ_27,+,lcl|NC_036025.1_cds_XP_022674188.1_649,612,TCTGCTACCAAGTGGATTGGTGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
27,READ_28,+,lcl|NC_036025.1_cds_XP_022674188.1_649,612,TCTGCTACCAAGTGGATTGGGGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>G
28,READ_29,+,lcl|NC_036032.1_cds_XP_022678348.1_4817,2019,TTATACAGAACTGGTGATTTAGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
29,READ_30,+,lcl|NC_036032.1_cds_XP_022678348.1_4817,2019,TTATACAGAACTGGTGATTTCGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:A>C
30,READ_31,+,lcl|NC_036032.1_cds_XP_022678348.1_4817,2019,TTATACAGAACTGGTGATTTTGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:A>T
31,READ_32,+,lcl|NC_036032.1_cds_XP_022678348.1_4817,2019,TTATACAGAACTGGTGATTTGGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:A>G

# rows with mismatches occuring after the 10th base should be dropped

In [13]:
# Create a new column called mismatch_position and extract the mismatch position digits from
# the mismatch column. Then fill NaN values with 0 because NaN means no mismatch.
# Then drop rows where the mismatch occurs after the 10th base.
df_a7_1mm_cds['mismatch_position'] = df_a7_1mm_cds['mismatch'].str.extract(r'(\d+):.*')[0]
df_a7_1mm_cds['mismatch_position'].fillna(0, inplace=True)
df_a7_1mm_cds['mismatch_position'] = df_a7_1mm_cds['mismatch_position'].astype(int)
df_a7_1mm_cds[df_a7_1mm_cds['mismatch_position'] < 10]

,query_name,strand,reference_name,mapping_position,Sequence,mapping_quality,idk,mismatch,mismatch_position
2,READ_3,+,lcl|NC_036025.1_cds_XP_022674188.1_649,618,ACCAAGTGGATTGGTGGTCATGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
7,READ_8,+,lcl|NC_036032.1_cds_XP_022678348.1_4817,1512,ACTCATTTGACACCAGCTATGGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
10,READ_11,+,lcl|NC_036025.1_cds_XP_022673914.1_374,273,ATTGGTGGTGCCATTGGTACTGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
14,READ_15,+,lcl|NC_036025.1_cds_XP_022674188.1_649,609,CACTCTGCTACCAAGTGGATTGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
18,READ_19,-,lcl|NC_036025.1_cds_XP_022673643.1_103,1434,CCATTCAAGGCCAAGTTCATGCC,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
20,READ_21,-,lcl|NC_036032.1_cds_XP_022678348.1_4817,1389,CCTATCCAAAGAGATATGTTCAC,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
26,READ_27,+,lcl|NC_036025.1_cds_XP_022674188.1_649,612,TCTGCTACCAAGTGGATTGGTGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
28,READ_29,+,lcl|NC_036032.1_cds_XP_022678348.1_4817,2019,TTATACAGAACTGGTGATTTAGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0

## A7 CDS 2MM

In [14]:
df_a7_2mm_cds = pd.read_csv('output/km_a7_2mm_cds_alignment.sam', sep='\t',
                names=['query_name', 'strand', 'reference_name', 'mapping_position',
                       'Sequence', 'mapping_quality', 'idk', 'mismatch'])
df_a7_2mm_cds

,query_name,strand,reference_name,mapping_position,Sequence,mapping_quality,idk,mismatch
0,READ_1,+,lcl|NC_036025.1_cds_XP_022674188.1_649,618,ACCAAGTGGATTGGTGGTCAAGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>A
1,READ_2,+,lcl|NC_036025.1_cds_XP_022674188.1_649,618,ACCAAGTGGATTGGTGGTCACGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>C
2,READ_3,+,lcl|NC_036025.1_cds_XP_022674188.1_649,618,ACCAAGTGGATTGGTGGTCATGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
3,READ_4,+,lcl|NC_036025.1_cds_XP_022674188.1_649,618,ACCAAGTGGATTGGTGGTCAGGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>G
4,READ_5,+,lcl|NC_036032.1_cds_XP_022678348.1_4817,1512,ACTCATTTGACACCAGCTATAGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:G>A
5,READ_6,+,lcl|NC_036032.1_cds_XP_022678348.1_4817,1512,ACTCATTTGACACCAGCTATCGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:G>C
6,READ_7,+,lcl|NC_036032.1_cds_XP_022678348.1_4817,1512,ACTCATTTGACACCAGCTATTGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:G>T
7,READ_8,+,lcl|NC_036032.1_cds_XP_022678348.1_4817,1512,ACTCATTTGACACCAGCTATGGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
8,READ_9,+,lcl|NC_036025.1_cds_XP_022673914.1_374,273,ATTGGTGGTGCCATTGGTACAGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>A
9,READ_10,+,lcl|NC_036025.1_cds_XP_022673914.1_374,273,ATTGGTGGTGCCATTGGTACCGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>C
10,READ_11,+,lcl|NC_036025.1_cds_XP_022673914.1_374,273,ATTGGTGGTGCCATTGGTACTGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
11,READ_12,+,lcl|NC_036025.1_cds_XP_022673914.1_374,273,ATTGGTGGTGCCATTGGTACGGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>G
12,READ_13,+,lcl|NC_036025.1_cds_XP_022674188.1_649,609,CACTCTGCTACCAAGTGGATAGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>A
13,READ_14,+,lcl|NC_036025.1_cds_XP_022674188.1_649,609,CACTCTGCTACCAAGTGGATCGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>C
14,READ_15,+,lcl|NC_036025.1_cds_XP_022674188.1_649,609,CACTCTGCTACCAAGTGGATTGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
15,READ_16,+,lcl|NC_036025.1_cds_XP_022674188.1_649,609,CACTCTGCTACCAAGTGGATGGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>G
16,READ_17,-,lcl|NC_036025.1_cds_XP_022673643.1_103,1434,CCTTTCAAGGCCAAGTTCATGCC,IIIIIIIIIIIIIIIIIIIIIII,0,20:A>T
17,READ_18,-,lcl|NC_036025.1_cds_XP_022673643.1_103,1434,CCGTTCAAGGCCAAGTTCATGCC,IIIIIIIIIIIIIIIIIIIIIII,0,20:A>G
18,READ_19,-,lcl|NC_036025.1_cds_XP_022673643.1_103,1434,CCATTCAAGGCCAAGTTCATGCC,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
19,READ_20,-,lcl|NC_036025.1_cds_XP_022673643.1_103,1434,CCCTTCAAGGCCAAGTTCATGCC,IIIIIIIIIIIIIIIIIIIIIII,0,20:A>C
20,READ_21,-,lcl|NC_036032.1_cds_XP_022678348.1_4817,1389,CCTATCCAAAGAGATATGTTCAC,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
21,READ_22,-,lcl|NC_036032.1_cds_XP_022678348.1_4817,1389,CCGATCCAAAGAGATATGTTCAC,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>G
22,READ_23,-,lcl|NC_036032.1_cds_XP_022678348.1_4817,1389,CCAATCCAAAGAGATATGTTCAC,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>A
23,READ_24,-,lcl|NC_036032.1_cds_XP_022678348.1_4817,1389,CCCATCCAAAGAGATATGTTCAC,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>C
24,READ_25,+,lcl|NC_036025.1_cds_XP_022674188.1_649,612,TCTGCTACCAAGTGGATTGGAGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>A
25,READ_26,+,lcl|NC_036025.1_cds_XP_022674188.1_649,612,TCTGCTACCAAGTGGATTGGCGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>C
26,READ_27,+,lcl|NC_036025.1_cds_XP_022674188.1_649,612,TCTGCTACCAAGTGGATTGGTGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
27,READ_28,+,lcl|NC_036025.1_cds_XP_022674188.1_649,612,TCTGCTACCAAGTGGATTGGGGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>G
28,READ_29,+,lcl|NC_036032.1_cds_XP_022678348.1_4817,2019,TTATACAGAACTGGTGATTTAGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
29,READ_30,+,lcl|NC_036032.1_cds_XP_022678348.1_4817,2019,TTATACAGAACTGGTGATTTCGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:A>C
30,READ_31,+,lcl|NC_036032.1_cds_XP_022678348.1_4817,2019,TTATACAGAACTGGTGATTTTGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:A>T
31,READ_32,+,lcl|NC_036032.1_cds_XP_022678348.1_4817,2019,TTATACAGAACTGGTGATTTGGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:A>G

# rows with mismatches occuring after the 10th base should be dropped

In [15]:
# Create a new column called mismatch_position and extract the mismatch position digits from
# the mismatch column. Then fill NaN values with 0 because NaN means no mismatch.
# Then drop rows where the mismatch occurs after the 10th base.
df_a7_2mm_cds['mismatch_position'] = df_a7_2mm_cds['mismatch'].str.extract(r'(\d+):.*')[0]
df_a7_2mm_cds['mismatch_position'].fillna(0, inplace=True)
df_a7_2mm_cds['mismatch_position'] = df_a7_2mm_cds['mismatch_position'].astype(int)
df_a7_2mm_cds[df_a7_2mm_cds['mismatch_position'] < 10]

,query_name,strand,reference_name,mapping_position,Sequence,mapping_quality,idk,mismatch,mismatch_position
2,READ_3,+,lcl|NC_036025.1_cds_XP_022674188.1_649,618,ACCAAGTGGATTGGTGGTCATGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
7,READ_8,+,lcl|NC_036032.1_cds_XP_022678348.1_4817,1512,ACTCATTTGACACCAGCTATGGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
10,READ_11,+,lcl|NC_036025.1_cds_XP_022673914.1_374,273,ATTGGTGGTGCCATTGGTACTGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
14,READ_15,+,lcl|NC_036025.1_cds_XP_022674188.1_649,609,CACTCTGCTACCAAGTGGATTGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
18,READ_19,-,lcl|NC_036025.1_cds_XP_022673643.1_103,1434,CCATTCAAGGCCAAGTTCATGCC,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
20,READ_21,-,lcl|NC_036032.1_cds_XP_022678348.1_4817,1389,CCTATCCAAAGAGATATGTTCAC,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
26,READ_27,+,lcl|NC_036025.1_cds_XP_022674188.1_649,612,TCTGCTACCAAGTGGATTGGTGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
28,READ_29,+,lcl|NC_036032.1_cds_XP_022678348.1_4817,2019,TTATACAGAACTGGTGATTTAGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0

## A7 GENOMIC 0MM

In [16]:
import pandas as pd

df_a7_0mm_genomic = pd.read_csv('output/km_a7_0mm_genomic_alignment.sam', sep='\t',
                names=['query_name', 'strand', 'reference_name', 'mapping_position',
                       'Sequence', 'mapping_quality', 'idk', 'mismatch'])
df_a7_0mm_genomic

,query_name,strand,reference_name,mapping_position,Sequence,mapping_quality,idk,mismatch
0,READ_3,+,NC_036025.1,1415950,ACCAAGTGGATTGGTGGTCATGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
1,READ_8,-,NC_036032.1,662219,CCCATAGCTGGTGTCAAATGAGT,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
2,READ_11,-,NC_036025.1,799064,CCAGTACCAATGGCACCACCAAT,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
3,READ_15,+,NC_036025.1,1415941,CACTCTGCTACCAAGTGGATTGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
4,READ_19,+,NC_036025.1,218078,GGCATGAACTTGGCCTTGAATGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
5,READ_21,+,NC_036032.1,662342,GTGAACATATCTCTTTGGATAGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
6,READ_27,+,NC_036025.1,1415944,TCTGCTACCAAGTGGATTGGTGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
7,READ_29,-,NC_036032.1,661712,CCTAAATCACCAGTTCTGTATAA,IIIIIIIIIIIIIIIIIIIIIII,0,NaN

## A7 GENOMIC 1MM

In [17]:
df_a7_1mm_genomic = pd.read_csv('output/km_a7_1mm_genomic_alignment.sam', sep='\t',
                names=['query_name', 'strand', 'reference_name', 'mapping_position',
                       'Sequence', 'mapping_quality', 'idk', 'mismatch'])
df_a7_1mm_genomic

,query_name,strand,reference_name,mapping_position,Sequence,mapping_quality,idk,mismatch
0,READ_1,+,NC_036025.1,1415950,ACCAAGTGGATTGGTGGTCAAGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>A
1,READ_2,+,NC_036025.1,1415950,ACCAAGTGGATTGGTGGTCACGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>C
2,READ_3,+,NC_036025.1,1415950,ACCAAGTGGATTGGTGGTCATGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
3,READ_4,+,NC_036025.1,1415950,ACCAAGTGGATTGGTGGTCAGGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>G
4,READ_5,-,NC_036032.1,662219,CCTATAGCTGGTGTCAAATGAGT,IIIIIIIIIIIIIIIIIIIIIII,0,20:C>T
5,READ_6,-,NC_036032.1,662219,CCGATAGCTGGTGTCAAATGAGT,IIIIIIIIIIIIIIIIIIIIIII,0,20:C>G
6,READ_7,-,NC_036032.1,662219,CCAATAGCTGGTGTCAAATGAGT,IIIIIIIIIIIIIIIIIIIIIII,0,20:C>A
7,READ_8,-,NC_036032.1,662219,CCCATAGCTGGTGTCAAATGAGT,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
8,READ_9,-,NC_036025.1,799064,CCTGTACCAATGGCACCACCAAT,IIIIIIIIIIIIIIIIIIIIIII,0,20:A>T
9,READ_10,-,NC_036025.1,799064,CCGGTACCAATGGCACCACCAAT,IIIIIIIIIIIIIIIIIIIIIII,0,20:A>G
10,READ_11,-,NC_036025.1,799064,CCAGTACCAATGGCACCACCAAT,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
11,READ_12,-,NC_036025.1,799064,CCCGTACCAATGGCACCACCAAT,IIIIIIIIIIIIIIIIIIIIIII,0,20:A>C
12,READ_13,+,NC_036025.1,1415941,CACTCTGCTACCAAGTGGATAGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>A
13,READ_14,+,NC_036025.1,1415941,CACTCTGCTACCAAGTGGATCGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>C
14,READ_15,+,NC_036025.1,1415941,CACTCTGCTACCAAGTGGATTGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
15,READ_16,+,NC_036025.1,1415941,CACTCTGCTACCAAGTGGATGGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>G
16,READ_17,+,NC_036025.1,218078,GGCATGAACTTGGCCTTGAAAGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>A
17,READ_18,+,NC_036025.1,218078,GGCATGAACTTGGCCTTGAACGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>C
18,READ_19,+,NC_036025.1,218078,GGCATGAACTTGGCCTTGAATGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
19,READ_20,+,NC_036025.1,218078,GGCATGAACTTGGCCTTGAAGGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>G
20,READ_21,+,NC_036032.1,662342,GTGAACATATCTCTTTGGATAGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
21,READ_22,+,NC_036032.1,662342,GTGAACATATCTCTTTGGATCGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:A>C
22,READ_23,+,NC_036032.1,662342,GTGAACATATCTCTTTGGATTGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:A>T
23,READ_24,+,NC_036032.1,662342,GTGAACATATCTCTTTGGATGGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:A>G
24,READ_25,+,NC_036025.1,1415944,TCTGCTACCAAGTGGATTGGAGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>A
25,READ_26,+,NC_036025.1,1415944,TCTGCTACCAAGTGGATTGGCGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>C
26,READ_27,+,NC_036025.1,1415944,TCTGCTACCAAGTGGATTGGTGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
27,READ_28,+,NC_036025.1,1415944,TCTGCTACCAAGTGGATTGGGGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>G
28,READ_29,-,NC_036032.1,661712,CCTAAATCACCAGTTCTGTATAA,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
29,READ_30,-,NC_036032.1,661712,CCGAAATCACCAGTTCTGTATAA,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>G
30,READ_31,-,NC_036032.1,661712,CCAAAATCACCAGTTCTGTATAA,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>A
31,READ_32,-,NC_036032.1,661712,CCCAAATCACCAGTTCTGTATAA,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>C

# rows with mismatches occuring after the 10th base should be dropped

In [18]:
# Create a new column called mismatch_position and extract the mismatch position digits from
# the mismatch column. Then fill NaN values with 0 because NaN means no mismatch.
# Then drop rows where the mismatch occurs after the 10th base.
df_a7_1mm_genomic['mismatch_position'] = df_a7_1mm_genomic['mismatch'].str.extract(r'(\d+):.*')[0]
df_a7_1mm_genomic['mismatch_position'].fillna(0, inplace=True)
df_a7_1mm_genomic['mismatch_position'] = df_a7_1mm_genomic['mismatch_position'].astype(int)
df_a7_1mm_genomic[df_a7_1mm_genomic['mismatch_position'] < 10]

,query_name,strand,reference_name,mapping_position,Sequence,mapping_quality,idk,mismatch,mismatch_position
2,READ_3,+,NC_036025.1,1415950,ACCAAGTGGATTGGTGGTCATGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
7,READ_8,-,NC_036032.1,662219,CCCATAGCTGGTGTCAAATGAGT,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
10,READ_11,-,NC_036025.1,799064,CCAGTACCAATGGCACCACCAAT,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
14,READ_15,+,NC_036025.1,1415941,CACTCTGCTACCAAGTGGATTGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
18,READ_19,+,NC_036025.1,218078,GGCATGAACTTGGCCTTGAATGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
20,READ_21,+,NC_036032.1,662342,GTGAACATATCTCTTTGGATAGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
26,READ_27,+,NC_036025.1,1415944,TCTGCTACCAAGTGGATTGGTGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
28,READ_29,-,NC_036032.1,661712,CCTAAATCACCAGTTCTGTATAA,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0

## A7 GENOMIC 2MM

In [19]:
df_a7_2mm_genomic = pd.read_csv('output/km_a7_2mm_genomic_alignment.sam', sep='\t',
                names=['query_name', 'strand', 'reference_name', 'mapping_position',
                       'Sequence', 'mapping_quality', 'idk', 'mismatch'])
df_a7_2mm_genomic

,query_name,strand,reference_name,mapping_position,Sequence,mapping_quality,idk,mismatch
0,READ_1,+,NC_036025.1,1415950,ACCAAGTGGATTGGTGGTCAAGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>A
1,READ_2,+,NC_036025.1,1415950,ACCAAGTGGATTGGTGGTCACGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>C
2,READ_3,+,NC_036025.1,1415950,ACCAAGTGGATTGGTGGTCATGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
3,READ_4,+,NC_036025.1,1415950,ACCAAGTGGATTGGTGGTCAGGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>G
4,READ_5,-,NC_036032.1,662219,CCTATAGCTGGTGTCAAATGAGT,IIIIIIIIIIIIIIIIIIIIIII,0,20:C>T
5,READ_6,-,NC_036032.1,662219,CCGATAGCTGGTGTCAAATGAGT,IIIIIIIIIIIIIIIIIIIIIII,0,20:C>G
6,READ_7,-,NC_036032.1,662219,CCAATAGCTGGTGTCAAATGAGT,IIIIIIIIIIIIIIIIIIIIIII,0,20:C>A
7,READ_8,-,NC_036032.1,662219,CCCATAGCTGGTGTCAAATGAGT,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
8,READ_9,-,NC_036025.1,799064,CCTGTACCAATGGCACCACCAAT,IIIIIIIIIIIIIIIIIIIIIII,0,20:A>T
9,READ_10,-,NC_036025.1,799064,CCGGTACCAATGGCACCACCAAT,IIIIIIIIIIIIIIIIIIIIIII,0,20:A>G
10,READ_11,-,NC_036025.1,799064,CCAGTACCAATGGCACCACCAAT,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
11,READ_12,-,NC_036025.1,799064,CCCGTACCAATGGCACCACCAAT,IIIIIIIIIIIIIIIIIIIIIII,0,20:A>C
12,READ_13,+,NC_036025.1,1415941,CACTCTGCTACCAAGTGGATAGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>A
13,READ_14,+,NC_036025.1,1415941,CACTCTGCTACCAAGTGGATCGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>C
14,READ_15,+,NC_036025.1,1415941,CACTCTGCTACCAAGTGGATTGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
15,READ_16,+,NC_036025.1,1415941,CACTCTGCTACCAAGTGGATGGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>G
16,READ_17,+,NC_036025.1,218078,GGCATGAACTTGGCCTTGAAAGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>A
17,READ_18,+,NC_036025.1,218078,GGCATGAACTTGGCCTTGAACGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>C
18,READ_19,+,NC_036025.1,218078,GGCATGAACTTGGCCTTGAATGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
19,READ_20,+,NC_036025.1,218078,GGCATGAACTTGGCCTTGAAGGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>G
20,READ_21,+,NC_036032.1,662342,GTGAACATATCTCTTTGGATAGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
21,READ_22,+,NC_036032.1,662342,GTGAACATATCTCTTTGGATCGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:A>C
22,READ_23,+,NC_036032.1,662342,GTGAACATATCTCTTTGGATTGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:A>T
23,READ_24,+,NC_036032.1,662342,GTGAACATATCTCTTTGGATGGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:A>G
24,READ_25,+,NC_036025.1,1415944,TCTGCTACCAAGTGGATTGGAGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>A
25,READ_26,+,NC_036025.1,1415944,TCTGCTACCAAGTGGATTGGCGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>C
26,READ_27,+,NC_036025.1,1415944,TCTGCTACCAAGTGGATTGGTGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
27,READ_28,+,NC_036025.1,1415944,TCTGCTACCAAGTGGATTGGGGG,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>G
28,READ_29,-,NC_036032.1,661712,CCTAAATCACCAGTTCTGTATAA,IIIIIIIIIIIIIIIIIIIIIII,0,NaN
29,READ_30,-,NC_036032.1,661712,CCGAAATCACCAGTTCTGTATAA,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>G
30,READ_31,-,NC_036032.1,661712,CCAAAATCACCAGTTCTGTATAA,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>A
31,READ_32,-,NC_036032.1,661712,CCCAAATCACCAGTTCTGTATAA,IIIIIIIIIIIIIIIIIIIIIII,0,20:T>C

# rows with mismatches occuring after the 10th base should be dropped

In [20]:
# Create a new column called mismatch_position and extract the mismatch position digits from
# the mismatch column. Then fill NaN values with 0 because NaN means no mismatch.
# Then drop rows where the mismatch occurs after the 10th base.
df_a7_2mm_genomic['mismatch_position'] = df_a7_2mm_genomic['mismatch'].str.extract(r'(\d+):.*')[0]
df_a7_2mm_genomic['mismatch_position'].fillna(0, inplace=True)
df_a7_2mm_genomic['mismatch_position'] = df_a7_2mm_genomic['mismatch_position'].astype(int)
df_a7_2mm_genomic[df_a7_2mm_genomic['mismatch_position'] < 10]

,query_name,strand,reference_name,mapping_position,Sequence,mapping_quality,idk,mismatch,mismatch_position
2,READ_3,+,NC_036025.1,1415950,ACCAAGTGGATTGGTGGTCATGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
7,READ_8,-,NC_036032.1,662219,CCCATAGCTGGTGTCAAATGAGT,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
10,READ_11,-,NC_036025.1,799064,CCAGTACCAATGGCACCACCAAT,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
14,READ_15,+,NC_036025.1,1415941,CACTCTGCTACCAAGTGGATTGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
18,READ_19,+,NC_036025.1,218078,GGCATGAACTTGGCCTTGAATGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
20,READ_21,+,NC_036032.1,662342,GTGAACATATCTCTTTGGATAGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
26,READ_27,+,NC_036025.1,1415944,TCTGCTACCAAGTGGATTGGTGG,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0
28,READ_29,-,NC_036032.1,661712,CCTAAATCACCAGTTCTGTATAA,IIIIIIIIIIIIIIIIIIIIIII,0,NaN,0